### ISSUE TITLE
B1 is out!

### ISSUE THREAD

**Issue by remotevase** [remotevase/DevMine#3]
Beta number 1 is out! Yay! The only problem: well, you can see it for yourself. Download the zip, unzip it, and run start.cmd. Then, enter your answer to the first step of the installer, and you will see the problem. I do not understand how to fix it...

**Comment by remotevase** [comment]
@AmiroEmad @Ad5001 @keithkfng @taki21 @phpdude CAN SOMEONE HELP ME FIX THIS?!?!?!

**Comment by Taki21** [comment]
u did this all ur self?

**Comment by Taki21** [comment]
the setup and code?

**Comment by Taki21** [comment]
If u did u should be the new PHP professor Lol

**Comment by Taki21** [comment]
Im gonna test now

**Comment by Taki21** [comment]
breh extracting 20 KBS weally?

**Comment by Taki21** [comment]
`Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(C:\Users\hossa\Desktop\DEVMINE\src/devmine/languages/Installer/,C:\Users\hossa\Desktop\DEVMINE\src/devmine/languages/Installer/): The system cannot find the path specified. (code: 3) in C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php:26
Stack trace:
#0 C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php(26): DirectoryIterator->__construct('C:\\Users\\hossa\\...')
#1 C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\Installer.php(40): devmine\utilities\installer\InstallerLang->__construct('eng')
#2 C:\Users\hossa\Desktop\DEVMINE\src\devmine\server\DevMine.php(435): devmine\utilities\installer\Installer->__construct()
#3 {main}
  thrown in C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php on line 26
`

**Comment by Taki21** [comment]
Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(C:\Users\hossa\Desktop\DEVMINE\src/devmine/languages/Installer/,C:\Users\hossa\Desktop\DEVMINE\src/devmine/languages/Installer/): The system cannot find the path specified. (code: 3) in C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php:26
Stack trace:
#0 C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php(26): DirectoryIterator->__construct('C:\Users\hossa\...')
#1 C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\Installer.php(40): devmine\utilities\installer\InstallerLang->__construct('eng')
#2 C:\Users\hossa\Desktop\DEVMINE\src\devmine\server\DevMine.php(435): devmine\utilities\installer\Installer->__construct()
#3 {main}
  thrown in C:\Users\hossa\Desktop\DEVMINE\src\devmine\utilities\installer\InstallerLang.php on line 26

**Comment by Taki21** [comment]
**DevMine B.1** thats a good tag is it?

**Comment by remotevase** [comment]
Well, no upload until stable version 1...

**Comment by remotevase** [comment]
How u fix this error? dats why I asked for u guys!

**Comment by remotevase** [comment]
@Taki21 
@AmiroEmad 
@Ad5001
@applqpak
@keithkfng
SOMEONE PLEASE HELP!!

**Comment by Ad5001** [comment]
I have no idea....

**Comment by Ad5001** [comment]
It seems like the path changing made this error. you need to rebase all the pases on the new ones

**Comment by MiroTheSuperDev** [comment]
i think you have to rebase all php files on the new paths

**Comment by MiroTheSuperDev** [comment]
wait i found i just said the same thing @Ad5001 said lol

**Comment by remotevase** [comment]
I already did that

**Comment by MiroTheSuperDev** [comment]
remote you didnt give us write access how should we help

**Comment by MiroTheSuperDev** [comment]
@remotevase @Taki21 @Ad5001 accept invitation here https://github.com/minedevelopers

and @remotevase move the respiratory to there if you please

**Comment by remotevase** [comment]
DA hell! I thought I added you! Anyways, the org name will be changed to DM Corporation AKA DM Corp

**Comment by remotevase** [comment]
Also, I'm not an owner of that org, so I can't create new repositories

**Comment by Super35** [comment]
@remotevase  do you want to be a Owner or Admin of my server ?

**Comment by Super35** [comment]
https://minecraftpocket-servers.com/server/48402 for ip changes

Ip changes every day

**Comment by remotevase** [comment]
@TheProest35YT you should use no-ip

**Comment by remotevase** [comment]
Adminplz, BC owner is too much responsibility

**Comment by MiroTheSuperDev** [comment]
@remotevase when he tell you ip changes everyday this means 

1- he is port forwading

2- he didnt set his ip as stable 

3- the server wont get good players amount

4- he is posting in our issue tracker about his server

**Comment by MiroTheSuperDev** [comment]
@remotevase @Taki21 @Ad5001 i promoted 3 of you to owners on https://github.com/minedevelopers

you may change the org name if you want @remotevase all we want before you change org name is moving the respiratory to there

**Comment by MiroTheSuperDev** [comment]
changed name to http://github.com/minecodes

**Comment by remotevase** [comment]
@AmiroEmad
1. Will upload repo tomorrow
2. Please add TheProest35YT (write access), and keithkfng (owner)

**Comment by Super35** [comment]
@remotevase i do not use portfowarding 

1: i use a website called https://server.pro

2: https://server.pro changes the ip for me

3: i cant change the ip its chosen by https://server.pro
- im not advertising-

**Comment by Super35** [comment]
@remotevase whats your mcpe name

**Comment by remotevase** [comment]
# master + remotevase

masteremotevase (me)

**Comment by Super35** [comment]
Ok done but your UltimateRanks plugin cant make Ranks

**Comment by remotevase** [comment]
No command for ultimateranks. Must use config

**Comment by Super35** [comment]
How

**Comment by Super35** [comment]
@remotevase or @amiroemad i do not use portfowarding

1: i use a website called https://server.pro

2: https://server.pro changes the ip for me

3: i cant change the ip its chosen by https://server.pro

im not advertising

**Comment by remotevase** [comment]
Read the description. It clearly says

```
Example Config:
[VIP]: player1
[VIP]: player2
[VIP+]: player3
[Other User]: player4
[VIP+]: player5
If a player's name is not listed in config, then that player will automatically be set to [Regular User] rank
```

Which means: Config should be

```
[Rank]: playername
```

**Comment by Super35** [comment]
Thanks ! @remotevase

**Comment by Super35** [comment]
@remotevase  why is your server ClearSky not ImagicalMine 1.5

**Comment by remotevase** [comment]
why? because ImagicalMine is not 0.15, and until @Ad5001 fixes it, I wont use ImagicalMine. I do not work on ImagicalMine anymore, so @Ad5001 should fix it,

**Comment by Ad5001** [comment]
What? I don't even know how to fix it and too busy rn ...

**Comment by MiroTheSuperDev** [comment]
@remotevase me too i wont use imagicalmine for the same reasons plus its buggy

**Comment by remotevase** [comment]
I just realized: I can finally say Taki21 real name! Hossa! Do ctrl+f and search for text below!

> C:\Users\hossa\Desktop\DEVMINE

**Comment by Taki21** [comment]
Thats not my real name silly :p

**Comment by Taki21** [comment]
its someone elses name cut off XD

**Comment by remotevase** [comment]
No duh... I can't find a single human being alive who has a first name of hossa...

**Comment by Taki21** [comment]
xD
